version: '3.9'

services:
  api:
    image: node:alpine
    container_name: api_nodejs
    command: 'npm run watch'
    env_file:
      - db.env
    volumes:
      - ./api:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 3333:3000
    networks:
      - docker-service
    depends_on:
      - db
  db:
    image: mariadb:latest
    container_name: docker-mariadb
    ports:
      - 3306:3306
    env_file:
      - ./db.env
    networks:
      - docker-service
    volumes:
      - ./data/api:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - docker-service

  apiUser:
    image: node:alpine
    container_name: api_user_nodejs
    command: 'npm run watch'
    env_file:
      - usr.env
    volumes:
      - ./apiUser:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 3330:3000
    networks:
      - docker-service
    depends_on:
      - dbUser
  dbUser:
    image: mariadb:latest
    container_name: docker-user-mariadb
    ports:
      - 3308:3306
    env_file:
      - ./usr.env
    networks:
      - docker-service
    volumes:
      - ./data/usr:/var/lib/mysql

networks:
  docker-service:
    driver: bridge
