version: '3.9'

services:
  api:
    image: node:alpine
    container_name: api_nodejs
    command: 'npm run watch'
    env_file:
      - .env
    working_dir: /usr/src/app
    ports:
      - 3333:3000
    volumes:
      - ./api:/usr/src/app
    networks:
      - some_network
    links:
      - mariadb
    depends_on:
      mariadb:
        condition: service_healthy 
  
  mariadb:
    image: mariadb
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/sql:/docker-entrypoint-initdb.d
    networks:
      - some_network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-p${MARIADB_ROOT_PASSWORD}"
        ]
      interval: 5s
      timeout: 5s
      retries: 20

networks:
  some_network:
    driver: bridge