version: '3.9'

services:
  api:
    image: node:alpine
    container_name: api_nodejs
    command: 'npm run watch'
    env_file:
      - ./api/.env
    volumes:
      - ./api:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 3333:3000 
    networks:
      - docker-service
    depends_on:
      - db
  db:
    image: mariadb:latest
    container_name: docker-mariadb
    ports:
      - 3306:3306
    env_file:
      - ./api/.env
    networks:
      - docker-service
    volumes: 
      - ./data:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - docker-service
  gateway:
    image: node:alpine
    container_name: gateway
    command: 'npm run watch'
    env_file:
      - ./gateway/.env
    volumes:
      - ./gateway:/usr/src/app/gateway
    working_dir: /usr/src/app/gateway
    ports:
      - 3001:3000
    links:
      - api
      - auth
    networks:
      - docker-service
networks:
  docker-service:
    driver: bridge