version: '3.9'

services:
  api:
    image: node:alpine
    container_name: api_nodejs
    command: 'npm run watch'
    env_file:
      - ./api/.env
    volumes:
      - ./api:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 3333:3000
    networks:
      - docker-service
    depends_on:
      - db
  db:
    image: mariadb:latest
    container_name: docker-mariadb
    ports:
      - 3306:3306
    env_file:
      - ./api/.env
    networks:
      - docker-service
    volumes: 
      - ./data:/data/db
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - docker-service
  auth:
    image: node:alpine
    container_name: auth_nodejs
    command: 'npm run watch'
    env_file:
      - ./auth/.env
    volumes:
      - ./auth:/usr/src/app/auth
    working_dir: /usr/src/app/auth
    ports:
      - 3334:3000
    networks:
      - service-auth
    depends_on:
      - dbauth
  dbauth:
    image: mariadb:latest
    container_name: mariadb-auth
    ports:
      - 3307:3306
    env_file:
      - ./auth/.env
    networks:
      - service-auth
    volumes: 
      - ./data-auth:/data/dbauth
  adminerauth:
    image: adminer
    ports:
      - 8081:8080
    networks:
      - service-auth
networks:
  service-auth:
    driver: bridge
  docker-service:
    driver: bridge